Caragay, Jhan Gabriel V.
2ECE-D

# A. REPRODUCIBLE NORMALIZATION PROBLEM

In [61]:
import numpy as np

In [62]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]])

In [63]:
S = (np.std(X))
print(S)

25.864075471588002


In [64]:
M = (X.mean())
print(M)

46.36


In [65]:
X_normalized = (X-M)/S
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [66]:
normalized_mean = np.mean(X_normalized)
print(normalized_mean)

0.0


In [67]:
normalized_std = np.std(X_normalized)
print(normalized_std)

0.9999999999999999


In [68]:
np.save("X_normalized.npy", X_normalized)

#B. Cubes Divisible by 4 Problem

In [69]:
C = np.arange(1,101).reshape(10,10) ** 3

np.set_printoptions(linewidth=300)
print(C)

[[      1       8      27      64     125     216     343     512     729    1000]
 [   1331    1728    2197    2744    3375    4096    4913    5832    6859    8000]
 [   9261   10648   12167   13824   15625   17576   19683   21952   24389   27000]
 [  29791   32768   35937   39304   42875   46656   50653   54872   59319   64000]
 [  68921   74088   79507   85184   91125   97336  103823  110592  117649  125000]
 [ 132651  140608  148877  157464  166375  175616  185193  195112  205379  216000]
 [ 226981  238328  250047  262144  274625  287496  300763  314432  328509  343000]
 [ 357911  373248  389017  405224  421875  438976  456533  474552  493039  512000]
 [ 531441  551368  571787  592704  614125  636056  658503  681472  704969  729000]
 [ 753571  778688  804357  830584  857375  884736  912673  941192  970299 1000000]]


In [70]:
C.shape

(10, 10)

In [87]:
div_by_4 = C[C % 4 == 0]
div_by_4

array([      8,      64,     216,     512,    1000,    1728,    2744,    4096,    5832,    8000,   10648,   13824,   17576,   21952,   27000,   32768,   39304,   46656,   54872,   64000,   74088,   85184,   97336,  110592,  125000,  140608,  157464,  175616,  195112,  216000,  238328,  262144,
        287496,  314432,  343000,  373248,  405224,  438976,  474552,  512000,  551368,  592704,  636056,  681472,  729000,  778688,  830584,  884736,  941192, 1000000])

In [85]:
div_by_4.size

50

In [73]:
np.save("div_by_4", div_by_4)

#C. Above-mean Squares Problem

In [74]:
S = np.arange(1,37).reshape(6,6) ** 2
S

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

In [75]:
S_mean = (S.mean())
print(S_mean)

450.1666666666667


In [76]:
above_mean = S[S > S_mean]
print(above_mean)

[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225 1296]


In [81]:
above_mean.size

15

In [77]:
np.save("above_mean.npy",above_mean)